[package]
name = "clap_serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["string"]}
serde = { version = "1"}

[dev-dependencies]
toml = {version = "0.5.8"}
